HomeWork 9
yurapukish/AutomationCourse pull request #12
Opened 2023-07-07 06:46 UTC by yurapukish

2023-07-08 07:04 UTC, antohaUa requested changes

2023-07-08 07:04 UTC, antohaUa commented on Lessons9/HomeWork.py
> +        output_file.writelines(f'{el:^7} -> {text.index(el):^7}\n'
Solution has gaps. You see if letters will be NOT unique - you will get incorrect positions. Just try to add additional 'e' at the beginning of input file. Thus probably findall not the best option here.

2023-07-08 19:42 UTC, yurapukish commented
hello, Update code
Change findall to finditer

2023-07-09 06:04 UTC, antohaUa approved these changes

2023-07-09 06:04 UTC, antohaUa commented on Lessons9/HomeWork.py
> +        with open('input.txt', 'r') as input_file:
Please pay attention that Read/Write IO operations are time consuming. Thus better if possible reduce file operations and reduce time when file is open. In your case the best option read file first-> prepare data -> in separate block write to file. Not so critical , but just keep it in mind

2023-07-09 06:04 UTC, antohaUa commented on Lessons9/HomeWork.py
> +        output_file.writelines(f'{el.group():^7} -> {el.start():^7}\n'
For readability better split this line into two:   list comprehension first and then  output_file.writelines(lc)

2023-07-09 06:04 UTC, antohaUa commented on Lessons9/HomeWork.py
> +            matches = re.finditer(r'[a-zA-Z]', text)
exactly!
you see findall not able to cover all regex cases - so you always should choose between match/search/findall/finditer - to find smth which best suits your needs )

2023-07-09 20:56 UTC, merged