OOP Home work 1. Reflect card flow
yurapukish/AutomationCourse pull request #18
Opened 2023-08-11 17:08 UTC by yurapukish

Hello, happy to reach you.
Reflect card flow:
1) Add few static and class methods
2) Use getters & setters
3) Add game for you

2023-08-14 15:42 UTC, antohaUa requested changes

2023-08-14 15:42 UTC, antohaUa commented on OOP_Les1/Home.py
> +        return f'Created new Bank card for {self.name, self.surname}'
Minor - > here should be not "Created" but smth aka "BankCard for ..."

2023-08-14 15:42 UTC, antohaUa commented on OOP_Les1/Home.py
> +        self._cvv = cvv
cvv better create as private attribute

2023-08-14 15:42 UTC, antohaUa commented on OOP_Les1/Home.py
> +    def get_exchange_rate(cls, rate):
This method is not used )) Please add this method usage into withdraw logic

2023-08-14 15:42 UTC, antohaUa commented on OOP_Les1/Home.py
> +        self.balance = BankCard.Card_Credit_Limit
Seems for balance we need setter and getter and this value better to add as key-> value param to init with default value == BankCard.Card_Credit_Limit.  Also pay attention that balance should be private or protected member - cause we should NOT allow modify it without additional checks

2023-08-14 15:42 UTC, antohaUa commented on OOP_Les1/Home.py
> +        if sum > self.balance:
Also please add here logic that payment not allowed if card.end_date expired

2023-08-21 06:23 UTC, yurapukish commented
Hello Updated code, did all changes that were requested

2023-08-22 09:08 UTC, antohaUa approved these changes

2023-08-22 09:08 UTC, antohaUa commented on OOP_Les1/Home.py
> +        date = datetime.now()
For date and time comparison better to use best practice 
See examples here
https://pynative.com/python-compare-dates/

2023-08-22 11:57 UTC, merged